### PR TITLE
Fix \@category and +project sorting

### LINKED ISSUE #30: Bad sorting with + inside todo text
```
(B) Linear regression Rnet=Qh+Qle. +cons_emp_model
(A) Review key questions. +benchmarking
(B) simple model first +cons_emp_model
```

This is the sorted result with `<leader>s+`.  the +Qle is not a project, and so it shouldn't be included in the sorting. A project needs to have a space before it, according to the spec, and in this case it doesn't. Bad regex?

### PR DESCRIPTION
**Pull request by naught101**
fixes #30 

This seems to fix the problem for me, but check before merging.

### CODE REVIEW

**Comment by freitass** [comment]
This fix doesn

**Comment by freitass** [comment]
This fix doesn't take into account projects/contexts at the beginning of the lines, but thanks for pointing out the issue.

**Comment by naught101** [comment]
according to the [spec](https://github.com/ginatrapani/todo.txt-cli/wiki/The-Todo.txt-Format):

> A context is preceded by a single space and an @ sign. A project is preceded by a single space and a plus + sign.

So it seems that projects/contexts at the start of a line are invalid anyway...

**Comment by naught101** [comment]
ok, maybe that's not clear in the spec, because there is an example where a context is used at the start of a line. So, the match should be *either* at the start of the line, or with a space before it..

**Comment by freitass** [comment]
Sorry, I didn't mean to be rude. I already have the fix (actually it was on the syntax file), I was just trying to check your other pull request before pulling both fixes to Github.

**Comment by naught101** [comment]
Ok, cool. This branch now has another commit that fixes the leading contaxt/project issue, if that's still relevant.

**Pull request closed without merging**
